name: Build Ultra Linux ISO
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Runner Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools xorriso debootstrap squashfs-tools grub-pc-bin grub-efi-amd64-bin

      - name: Build Base System
        run: |
          mkdir -p chroot
          sudo debootstrap --variant=minbase --arch=amd64 stable chroot http://deb.debian.org/debian/
          
          # تجهيز بيئة النظام الداخلي عشان apt يشتغل بدون أخطاء
          sudo mount --bind /dev chroot/dev
          sudo mount -t proc /proc chroot/proc
          sudo mount -t sysfs /sys chroot/sys

          # إعداد المستخدمين (اليوزر: admin | الباسورد: admin)
          sudo chroot chroot /bin/bash -c "useradd -m -s /bin/bash admin && echo 'admin:admin' | chpasswd"
          sudo chroot chroot /bin/bash -c "echo 'root:admin' | chpasswd"

      - name: Inject Files and Run Install
        run: |
          sudo cp .jwmrc chroot/etc/skel/
          sudo cp wallpaper.jpg chroot/etc/skel/.wallpaper.jpg
          sudo cp install.sh chroot/root/
          
          sudo bash -c "echo 'if [[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]]; then exec startx; fi' >> chroot/etc/skel/.bash_profile"
          
          # تشغيل سكريبت التثبيت
          sudo chroot chroot /bin/bash -c "chmod +x /root/install.sh && /root/install.sh"

      - name: Clean Up Mounts
        run: |
          # فك الارتباط عشان بناء الـ ISO يتم بنجاح
          sudo umount chroot/sys
          sudo umount chroot/proc
          sudo umount chroot/dev

      - name: Generate ISO
        run: |
          mkdir -p output
          sudo grub-mkrescue -o output/Ultra-Linux.iso chroot

      - name: Upload Final ISO
        uses: actions/upload-artifact@v4
        with:
          name: Ultra-Linux-ISO
          path: output/Ultra-Linux.iso
